# fly.toml file generated for demo-drop on 2024-08-07T22:00:00.000Z

app = "demo-drop"
primary_region = "sea" # Seattle, WA.

[build]

[http_service]
  internal_port = 8090
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

[mounts]
  source="pb_data"
  destination="/pb_data" 